<?php
namespace backend\components;
use yii\base\ActionFilter;
use yii\web\HttpException;
class RbacFilter extends ActionFilter{
    private static $noCheckActions=['admin/login','admin/logout'];
    public function beforeAction($action)
    {
        $user=\yii::$app->user;
        if(in_array($action->uniqueId,self::$noCheckActions)){
        }
        elseif(!$user->can($action->uniqueId)){
            //用户未登录，引导用户先登录
            if($user->isGuest){
                return $action->controller->redirect($user->loginUrl);
            }
            throw new HttpException(403,'对不起，您没有该权限');
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}